//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStar {
    
    
    public partial class DanhSachSanPham {
        
        /// <summary>
        /// idUCDanhMucSanPham control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShoppingHere.Controls.ucDanhMucSanPham idUCDanhMucSanPham;
        
        /// <summary>
        /// ucDSSanPham control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShoppingHere.Controls.ucDanhSachSanPham ucDSSanPham;
        
        /// <summary>
        /// UcThongTinTaiKhoan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShoppingHere.Controls.ucThongTinTaiKhoan UcThongTinTaiKhoan;
    }
}
