//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStar {
    
    
    public partial class DanhSachSanPham {
        
        /// <summary>
        /// idUCDanhMucSanPham1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SuperStar.Controls.ucDanhMucSanPham idUCDanhMucSanPham1;
        
        /// <summary>
        /// ucDSSanPham control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SuperStar.Controls.ucDanhSachSanPham ucDSSanPham;
        
        /// <summary>
        /// UcThongTinTaiKhoan1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SuperStar.Controls.ucThongTinTaiKhoan UcThongTinTaiKhoan1;
    }
}
