//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStar {
    
    
    public partial class TrangCaNhan {
        
        /// <summary>
        /// idUCDanhMucSanPham control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SuperStar.Controls.ucDanhMucSanPham idUCDanhMucSanPham;
        
        /// <summary>
        /// ucThongTinCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SuperStar.Controls.ucThongTinCaNhan ucThongTinCaNhan;
        
        /// <summary>
        /// ucDSDonDatHang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SuperStar.Controls.ucDanhSachDonDatHang ucDSDonDatHang;
        
        /// <summary>
        /// ucQuanLySanPham control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SuperStar.Controls.ucQuanLySanPham ucQuanLySanPham;
        
        /// <summary>
        /// ucQuanLyTaiKhoan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SuperStar.Controls.ucQuanLyTaiKhoan ucQuanLyTaiKhoan;
        
        /// <summary>
        /// UCThongTinTaiKhoan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SuperStar.Controls.ucThongTinTaiKhoan UCThongTinTaiKhoan;
    }
}
